
# This example demonstrates an experiment which starts two ReplicaSets with different images.
# While the experiment is running, it runs a job-based analysis, which performs HTTP benchmarking
# against each replicasets via their respective services.
apiVersion: argoproj.io/v1alpha1
kind: Experiment
metadata:
  name: experiment-demo
  labels:
    experiment: demo
spec:
  duration: 3m
  templates:
  - name: v1
    replicas: 2
    minReadySeconds: 10
    selector:
      matchLabels:
        app: rollouts-demo
        type: v1
    template:
      metadata:
        labels:
          app: rollouts-demo
          type: v1
      spec:
        containers:
        - name: rollouts-demo
          image: argoproj/rollouts-demo:purple
          imagePullPolicy: Always
          ports:
          - name: http
            containerPort: 8080
            protocol: TCP
  - name: v2
    minReadySeconds: 10
    replicas: 2
    selector:
      matchLabels:
        app: rollouts-demo
        type: v2
    template:
      metadata:
        labels:
          app: rollouts-demo
          type: v2
      spec:
        containers:
        - name: rollouts-demo
          # Note that this is intentionally using a "bad" version of the image, the bad image has a
          # high error rate, which will cause the experiment to fail prematurely
          image: argoproj/rollouts-demo:bad-orange
          imagePullPolicy: Always
          ports:
          - name: http
            containerPort: 8080
            protocol: TCP

  analyses:
  - name: v1
    templateName: http-benchmark
    args: [{name: host, value: rollouts-demo-v1}]
  - name: v2
    templateName: http-benchmark
    args: [{name: host, value: rollouts-demo-v2}]
